.TH "comp_list_t" 3 "Wed Sep 4 2013" "Compiladores 2013/2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
comp_list_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <comp_list\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBnode\fP"
.br
.ti -1c
.RI "struct \fBcomp_list_t\fP * \fBnext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBcomp_list_t\fP* \fBnext\fP"
.SS "int \fBnode\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Compiladores 2013/2 from the source code\&.
