.TH "include/comp_graph.h" 3 "Wed Sep 4 2013" "Compiladores 2013/2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/comp_graph.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBcomp_graph_t\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBcomp_graph_t\fP \fBGraph\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcreateGraph\fP (\fBGraph\fP *graph, int nodes)"
.br
.ti -1c
.RI "void \fBdestroyGraph\fP (\fBGraph\fP *graph)"
.br
.ti -1c
.RI "void \fBaddEdge\fP (\fBGraph\fP *graph, int i, int f)"
.br
.ti -1c
.RI "void \fBprintGraph\fP (\fBGraph\fP *graph)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBcomp_graph_t\fP  \fBGraph\fP"
.SH "Function Documentation"
.PP 
.SS "void \fBaddEdge\fP (\fBGraph\fP *graph, inti, intf)"
.SS "void \fBcreateGraph\fP (\fBGraph\fP *graph, intnodes)"
.SS "void \fBdestroyGraph\fP (\fBGraph\fP *graph)"
.SS "void \fBprintGraph\fP (\fBGraph\fP *graph)"
.SH "Author"
.PP 
Generated automatically by Doxygen for Compiladores 2013/2 from the source code\&.
