.TH "include/main.h" 3 "Wed Sep 4 2013" "Compiladores 2013/2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/main.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'comp_dict\&.h'\fP
.br
\fC#include 'comp_list\&.h'\fP
.br
\fC#include 'comp_tree\&.h'\fP
.br
\fC#include 'comp_graph\&.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBIKS_SYNTAX_SUCESSO\fP   0"
.br
.ti -1c
.RI "#define \fBIKS_SYNTAX_ERRO\fP   1"
.br
.ti -1c
.RI "#define \fBIKS_SIMBOLO_INDEFINIDO\fP   0"
.br
.ti -1c
.RI "#define \fBIKS_SIMBOLO_LITERAL_INT\fP   1"
.br
.ti -1c
.RI "#define \fBIKS_SIMBOLO_LITERAL_FLOAT\fP   2"
.br
.ti -1c
.RI "#define \fBIKS_SIMBOLO_LITERAL_CHAR\fP   3"
.br
.ti -1c
.RI "#define \fBIKS_SIMBOLO_LITERAL_STRING\fP   4"
.br
.ti -1c
.RI "#define \fBIKS_SIMBOLO_LITERAL_BOOL\fP   5"
.br
.ti -1c
.RI "#define \fBIKS_SIMBOLO_IDENTIFICADOR\fP   6"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBIKS_SIMBOLO_IDENTIFICADOR\fP   6"
.SS "#define \fBIKS_SIMBOLO_INDEFINIDO\fP   0"
.SS "#define \fBIKS_SIMBOLO_LITERAL_BOOL\fP   5"
.SS "#define \fBIKS_SIMBOLO_LITERAL_CHAR\fP   3"
.SS "#define \fBIKS_SIMBOLO_LITERAL_FLOAT\fP   2"
.SS "#define \fBIKS_SIMBOLO_LITERAL_INT\fP   1"
.SS "#define \fBIKS_SIMBOLO_LITERAL_STRING\fP   4"
.SS "#define \fBIKS_SYNTAX_ERRO\fP   1"
.SS "#define \fBIKS_SYNTAX_SUCESSO\fP   0"
.SH "Author"
.PP 
Generated automatically by Doxygen for Compiladores 2013/2 from the source code\&.
