.TH "nome_interno" 3 "Wed Sep 4 2013" "Compiladores 2013/2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nome_interno \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <comp_dict\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBtext\fP"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "int \fBintVal\fP"
.br
.ti -1c
.RI "char \fBcharVal\fP"
.br
.ti -1c
.RI "int \fBboolVal\fP"
.br
.ti -1c
.RI "struct \fBnome_interno\fP * \fBnext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fBboolVal\fP"
.SS "char \fBcharVal\fP"
.SS "int \fBintVal\fP"
.SS "struct \fBnome_interno\fP* \fBnext\fP"
.SS "char* \fBtext\fP"
.SS "int \fBtype\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Compiladores 2013/2 from the source code\&.
