.TH "parser.y" 3 "Wed Sep 4 2013" "Compiladores 2013/2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
parser.y \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'comp_dict\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "function \fB__pad0__\fP"
.br
.ti -1c
.RI "\fBlocal_var_decl\fP \fB__pad1__\fP"
.br
.ti -1c
.RI "\fBtype\fP \fB__pad2__\fP"
.br
.ti -1c
.RI "\fBlocal_var_decl\fP"
.br
.ti -1c
.RI "block \fB__pad3__\fP"
.br
.ti -1c
.RI "flow_block \fB__pad4__\fP"
.br
.ti -1c
.RI "simple_command_function \fB__pad5__\fP"
.br
.ti -1c
.RI "\fBTK_IDENTIFICADOR\fP = ' exp'"
.br
.ti -1c
.RI "\fBTK_PR_OUTPUT\fP \fBoutput\fP"
.br
.ti -1c
.RI "\fBTK_PR_RETURN\fP \fBreturn\fP"
.br
.ti -1c
.RI "global_var_decl \fB__pad6__\fP"
.br
.ti -1c
.RI "\fBtype\fP \fB__pad7__\fP"
.br
.ti -1c
.RI "simple_command \fB__pad8__\fP"
.br
.ti -1c
.RI "control_flow_command \fB__pad9__\fP"
.br
.ti -1c
.RI "\fBreturn\fP \fB__pad10__\fP"
.br
.ti -1c
.RI "param_list \fB__pad11__\fP"
.br
.ti -1c
.RI "param_list \fBtype\fP"
.br
.ti -1c
.RI "\fBcall_param_list\fP \fB__pad12__\fP"
.br
.ti -1c
.RI "\fBcall_param_list\fP constant \fBcall_param_list\fP"
.br
.ti -1c
.RI "exp \fB__pad13__\fP"
.br
.ti -1c
.RI "constant \fB__pad14__\fP"
.br
.ti -1c
.RI "\fBoutput\fP \fB__pad15__\fP"
.br
.ti -1c
.RI "\fBtype\fP \fB__pad16__\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "function \fB__pad0__\fP"
.SS "\fBreturn\fP \fB__pad10__\fP"
.SS "param_list \fB__pad11__\fP"
.SS "\fBcall_param_list\fP \fB__pad12__\fP"
.SS "exp \fB__pad13__\fP"
.SS "constant \fB__pad14__\fP"
.SS "\fBoutput\fP \fB__pad15__\fP"
.SS "\fBtype\fP \fB__pad16__\fP"
.SS "\fBlocal_var_decl\fP \fB__pad1__\fP"
.SS "\fBtype\fP \fB__pad2__\fP"
.SS "block \fB__pad3__\fP"
.SS "flow_block \fB__pad4__\fP"
.SS "simple_command_function \fB__pad5__\fP"
.SS "global_var_decl \fB__pad6__\fP"
.SS "\fBtype\fP \fB__pad7__\fP"
.SS "simple_command \fB__pad8__\fP"
.SS "control_flow_command \fB__pad9__\fP"
.SS "\fBcall_param_list\fP constant \fBTK_IDENTIFICADOR\fP ['exp'] \fBcall_param_list\fP"
.SS "\fBlocal_var_decl\fP"
.SS "\fBoutput\fP \fBoutput\fP"
.SS "\fBTK_PR_RETURN\fP \fBreturn\fP"
.SS "\fBTK_IDENTIFICADOR\fP['exp'] = ' exp'"
.SS "param_list \fBtype\fP"
.SH "Author"
.PP 
Generated automatically by Doxygen for Compiladores 2013/2 from the source code\&.
