.TH "scanner.l" 3 "Wed Sep 4 2013" "Compiladores 2013/2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scanner.l \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'string\&.h'\fP
.br
\fC#include 'stdlib\&.h'\fP
.br
\fC#include 'parser\&.h'\fP
.br
\fC#include 'main\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "\fB__pad17__\fP"
.br
.ti -1c
.RI "float \fBreturn\fP \fBTK_PR_FLOAT\fP"
.br
.ti -1c
.RI "bool \fBreturn\fP \fBTK_PR_BOOL\fP"
.br
.ti -1c
.RI "char \fBreturn\fP \fBTK_PR_CHAR\fP"
.br
.ti -1c
.RI "string \fBreturn\fP \fBTK_PR_STRING\fP"
.br
.ti -1c
.RI "if \fBreturn\fP \fBTK_PR_IF\fP"
.br
.ti -1c
.RI "then \fBreturn\fP \fBTK_PR_THEN\fP"
.br
.ti -1c
.RI "else \fBreturn\fP \fBTK_PR_ELSE\fP"
.br
.ti -1c
.RI "while \fBreturn\fP \fBTK_PR_WHILE\fP"
.br
.ti -1c
.RI "do \fBreturn\fP \fBTK_PR_DO\fP"
.br
.ti -1c
.RI "input \fBreturn\fP \fBTK_PR_INPUT\fP"
.br
.ti -1c
.RI "\fBoutput\fP \fBreturn\fP \fBTK_PR_OUTPUT\fP"
.br
.ti -1c
.RI "\fBreturn\fP \fBreturn\fP \fBTK_PR_RETURN\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fB__pad17__\fP"
.SS "bool \fBreturn\fP \fBTK_PR_BOOL\fP"
.SS "char \fBreturn\fP \fBTK_PR_CHAR\fP"
.SS "do \fBreturn\fP \fBTK_PR_DO\fP"
.SS "else \fBreturn\fP \fBTK_PR_ELSE\fP"
.SS "float \fBreturn\fP \fBTK_PR_FLOAT\fP"
.SS "if \fBreturn\fP \fBTK_PR_IF\fP"
.SS "input \fBreturn\fP \fBTK_PR_INPUT\fP"
.SS "\fBoutput\fP \fBreturn\fP \fBTK_PR_OUTPUT\fP"
.SS "\fBreturn\fP \fBreturn\fP \fBTK_PR_RETURN\fP"
.SS "string \fBreturn\fP \fBTK_PR_STRING\fP"
.SS "then \fBreturn\fP \fBTK_PR_THEN\fP"
.SS "while \fBreturn\fP \fBTK_PR_WHILE\fP"
.SH "Author"
.PP 
Generated automatically by Doxygen for Compiladores 2013/2 from the source code\&.
