.TH "include/tokens.h" 3 "Wed Sep 4 2013" "Compiladores 2013/2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/tokens.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBTK_PR_INT\fP   256   /* int       */"
.br
.ti -1c
.RI "#define \fBTK_PR_FLOAT\fP   257   /* float     */"
.br
.ti -1c
.RI "#define \fBTK_PR_BOOL\fP   258   /* bool      */"
.br
.ti -1c
.RI "#define \fBTK_PR_CHAR\fP   259   /* char      */"
.br
.ti -1c
.RI "#define \fBTK_PR_STRING\fP   260   /* string    */"
.br
.ti -1c
.RI "#define \fBTK_PR_IF\fP   261   /* if        */"
.br
.ti -1c
.RI "#define \fBTK_PR_THEN\fP   262   /* then      */"
.br
.ti -1c
.RI "#define \fBTK_PR_ELSE\fP   263   /* else      */"
.br
.ti -1c
.RI "#define \fBTK_PR_WHILE\fP   264   /* while     */"
.br
.ti -1c
.RI "#define \fBTK_PR_DO\fP   265   /* do        */"
.br
.ti -1c
.RI "#define \fBTK_PR_INPUT\fP   266   /* input     */"
.br
.ti -1c
.RI "#define \fBTK_PR_OUTPUT\fP   267   /* \fBoutput\fP    */"
.br
.ti -1c
.RI "#define \fBTK_PR_RETURN\fP   268   /* \fBreturn\fP    */"
.br
.ti -1c
.RI "#define \fBTK_OC_LE\fP   270   /* <=        */"
.br
.ti -1c
.RI "#define \fBTK_OC_GE\fP   271   /* >=        */"
.br
.ti -1c
.RI "#define \fBTK_OC_EQ\fP   272   /* ==        */"
.br
.ti -1c
.RI "#define \fBTK_OC_NE\fP   273   /* !=        */"
.br
.ti -1c
.RI "#define \fBTK_OC_AND\fP   274   /* &&        */"
.br
.ti -1c
.RI "#define \fBTK_OC_OR\fP   275   /* ||        */"
.br
.ti -1c
.RI "#define \fBTK_LIT_INT\fP   281"
.br
.ti -1c
.RI "#define \fBTK_LIT_FLOAT\fP   282"
.br
.ti -1c
.RI "#define \fBTK_LIT_FALSE\fP   283"
.br
.ti -1c
.RI "#define \fBTK_LIT_TRUE\fP   284"
.br
.ti -1c
.RI "#define \fBTK_LIT_CHAR\fP   285"
.br
.ti -1c
.RI "#define \fBTK_LIT_STRING\fP   286"
.br
.ti -1c
.RI "#define \fBTK_IDENTIFICADOR\fP   290"
.br
.ti -1c
.RI "#define \fBTOKEN_ERRO\fP   291"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "\fBcall_param_list\fP constant \fBTK_IDENTIFICADOR\fP   290"
.SS "#define \fBTK_LIT_CHAR\fP   285"
.SS "#define \fBTK_LIT_FALSE\fP   283"
.SS "#define \fBTK_LIT_FLOAT\fP   282"
.SS "#define \fBTK_LIT_INT\fP   281"
.SS "#define \fBTK_LIT_STRING\fP   286"
.SS "#define \fBTK_LIT_TRUE\fP   284"
.SS "#define \fBTK_OC_AND\fP   274   /* &&        */"
.SS "#define \fBTK_OC_EQ\fP   272   /* ==        */"
.SS "#define \fBTK_OC_GE\fP   271   /* >=        */"
.SS "#define \fBTK_OC_LE\fP   270   /* <=        */"
.SS "#define \fBTK_OC_NE\fP   273   /* !=        */"
.SS "#define \fBTK_OC_OR\fP   275   /* ||        */"
.SS "#define \fBTK_PR_BOOL\fP   258   /* bool      */"
.SS "#define \fBTK_PR_CHAR\fP   259   /* char      */"
.SS "#define \fBTK_PR_DO\fP   265   /* do        */"
.SS "#define \fBTK_PR_ELSE\fP   263   /* else      */"
.SS "#define \fBTK_PR_FLOAT\fP   257   /* float     */"
.SS "#define \fBTK_PR_IF\fP   261   /* if        */"
.SS "#define \fBTK_PR_INPUT\fP   266   /* input     */"
.SS "#define \fBTK_PR_INT\fP   256   /* int       */"
.SS "#define \fBTK_PR_OUTPUT\fP   267   /* \fBoutput\fP    */"
.SS "#define \fBTK_PR_RETURN\fP   268   /* \fBreturn\fP    */"
.SS "#define \fBTK_PR_STRING\fP   260   /* string    */"
.SS "#define \fBTK_PR_THEN\fP   262   /* then      */"
.SS "#define \fBTK_PR_WHILE\fP   264   /* while     */"
.SS "#define \fBTOKEN_ERRO\fP   291"
.SH "Author"
.PP 
Generated automatically by Doxygen for Compiladores 2013/2 from the source code\&.
